version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      development-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "typescript"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "wrangler"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "@cloudflare/workers-types"
        update-types:
          - "version-update:semver-major"
