name = "gridstart"
pages_build_output_dir = "dist"

compatibility_date = "2026-06-12"
compatibility_flags = ["nodejs_compat"]

[vars]
RATE_LIMIT_MAX = 5000

[env.production]
vars = { RATE_LIMIT_MAX = 2000 }
